---
- name: Allow traffic on chosen port
  ansible.builtin.include_tasks: firewall.yml

- name: Install and enable haproxy
  ansible.builtin.include_tasks: install.yml

- name: Deploy config
  ansible.builtin.include_tasks: deploy.yml
