---
- name: Web server validation
  ansible.builtin.include_tasks: web_server.yml
  when: "'web_servers' in group_names"

- name: Load balancer validation
  ansible.builtin.include_tasks: load_balancer.yml
  when: "'load_balancer' in group_names"
