---
web_server_port: 80
web_server_server_name: "{{ inventory_hostname }}.{{ env }}"
web_server_root: /usr/share/nginx/html
web_server_index: index.html
web_server_config_path: /etc/nginx/conf.d/default.conf
