---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy site config
  ansible.builtin.template:
    src: nginx_site.conf.j2
    dest: "{{ web_server_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_server_root }}/{{ web_server_index }}"
    owner: root
    group: root
    mode: "0644"

- name: Allow traffic on port 80
  ansible.posix.firewalld:
    port: 80/tcp
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: Allow traffic on port 443
  ansible.posix.firewalld:
    port: 443/tcp
    zone: public
    permanent: true
    immediate: true
    state: enabled
